### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by tekunotri** [tekunotri/technohud-tf2c#1]
- [ ] 4team stuff i forgot (ctf comes to mind, dom seems to be working fine)
- [x] fix some meters (cough chekhov)
- [ ] finish 4team ctf
- [ ] make vip huds
- [ ] remake/backport missing files
- [ ] whatever else i come by

small list as i find stuff
